#!/usr/bin/env python

from time import time
import asyncio as aio
loop = aio.get_event_loop()
import binance.websockets as ws

async def cr():
    names = [
            ws.aggregate_trades_name('NANOBTC'),
            ws.aggregate_trades_name('DGDBTC'),
            ]
    async with await ws.combined(names) as s:
        while True:
            print(await s.recv())
loop.run_until_complete(cr())
